name: Triggered workflow with Various Inputs

on:
  workflow_dispatch:
    inputs:
      run-test:
        description: "Run test?"
        type: boolean
        required: true
        default: false
      test-type:
        description: "Type of tests to run"
        type: choice
        options:
          - unit
          - integration
          - all
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
 
    steps:
      - name: Print hello
        if: ${{ inputs.run-test == 'false'}}
        run: echo "First test"
        
      - name: Run unit tests
        if: ${{ inputs.test-type == 'unit' }} || ${{ inputs.test-type == 'all' }}
        run: echo "Unit tests runtt"
        
      - name: Run integration test
        if:  ${{ inputs.test-type == 'integration' }} || ${{ inputs.test-type == 'all' }}
        run: echo "Integration runzz"
          
    
