name: Triggered workflow with Various Inputs

on:
  workflow_dispatch:
    inputs:
      run-test:
        description: "Run test?"
        type: boolean
        required: true
        default: false
      test-type:
        description: "Type of tests to run"
        type: choice
        options:
          - unit
          - integration
          - all
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{inputs.run-test == "true"}}
    steps:
      - name: Print hello
        run: echo "First test"
        
      - name: Run unit tests
        if: ${{ contains(['unit', 'all'], inputs.test-type) }}
        run: echo "Unit tests run"
        
      - name: Run integration test
        if: ${{ contains(['integration', 'all'], inputs.test-type) }}
        run: echo "Integration run"
          
    
